test_that("aggregation functions work", {
  expect_equal(mean_na(c(1,2,3)), 2)
  expect_equal(mean_na(c(1,2,NA)), 1.5)
  expect_equal(mean_na(1,2,3), 2)
  expect_equal(mean_na(1,2,NA), 1.5)
  expect_equal(mean_na(c(1,2),NA), 1.5)
  expect_equal(mean_na(NA,NA), NA_real_)
  expect_equal(sum_na(c(1,2,3)), 6)
  expect_equal(sum_na(c(1,2,NA)), 3)
  expect_equal(sum_na(1,2,3), 6)
  expect_equal(sum_na(1,2,NA), 3)
  expect_equal(sum_na(c(1,2),NA), 3)
  expect_equal(sum_na(NA,NA), NA_real_)
  expect_equal(min_na(c(1,2,3)), 1)
  expect_equal(min_na(c(1,2,NA)), 1)
  expect_equal(min_na(1,2,3), 1)
  expect_equal(min_na(1,2,NA), 1)
  expect_equal(min_na(c(1,2),NA), 1)
  expect_equal(min_na(NA,NA), NA_real_)
  expect_equal(max_na(c(1,2,3)), 3)
  expect_equal(max_na(c(1,2,NA)), 2)
  expect_equal(max_na(1,2,3), 3)
  expect_equal(max_na(1,2,NA), 2)
  expect_equal(max_na(c(1,2),NA), 2)
  expect_equal(max_na(NA,NA), NA_real_)
})
